GO := go

generate:
	go generate ./...

build: generate
	 go build ./...

unit-test:
	go test -race -mod=readonly ./...

lint:
	golangci-lint run ./...
	go fmt ./...

test:
	go test -race -mod=readonly -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./...
	go tool cover -html=coverage.txt -o coverage.html
